name: Supabase Sync

on:
  push:
    branches:
      - main

jobs:
  sync-schema:
    name: Sync Supabase Schema
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate schema.sql
        run: npx drizzle-kit generate:pg

      - name: Push to Supabase
        run: npx supabase db push

  audit-search-path:
    name: Audit & Fix Function Search Path
    runs-on: ubuntu-latest
    needs: sync-schema

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get install postgresql-client

      - name: Run audit script
        run: psql "$DATABASE_URL" -f supabase/audit/audit_search_path.sql
